Repository stolostron/multicluster-global-hub, pull requests merged in 2022-08, with the labels that each got.

#96 Fixed the E2E application test
  test/pkg/e2e/hoh-application_test.go
  test/pkg/e2e/hoh-cluster_test.go
Labels: lgtm, approved, dco-signoff: yes

#98 operator manages addon resources.
  go.mod
  go.sum
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/role.yaml
  operator/main.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#99 fix manifestwork apply failure.
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-namespace.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/04-policy-addon-controller.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/05-policy-propagator.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-hub-of-hubs-agent-applier.yaml
  operator/pkg/controllers/leafhub/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#100 handle hohconfig update and recreate.
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#101 support override operands images with annotation.
  operator/config/samples/hubofhubs_v1alpha1_config.yaml
  operator/pkg/config/hoh_config.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
  operator/pkg/controllers/hubofhubs/manifests/rbac/deployment.yaml
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-deployment.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-hub-of-hubs-agent-applier.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-deployment.yaml
  operator/pkg/controllers/leafhub/manifestwork.go
  operator/pkg/controllers/leafhub/template.go
Labels: lgtm, approved, dco-signoff: yes

#103 Add the postgres to HoH operator
  operator/apis/hubofhubs/v1alpha1/config_types.go
  operator/apis/hubofhubs/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/hubofhubs.open-cluster-management.io_configs.yaml
  operator/pkg/controllers/hubofhubs/conditions.go
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/hubofhubs/database/1.schemas.sql
  operator/pkg/controllers/hubofhubs/database/2.functions.sql
  operator/pkg/controllers/hubofhubs/database/3.tables.sql
  operator/pkg/controllers/hubofhubs/database/4.authorize.sql
  operator/pkg/controllers/hubofhubs/database/5.trigger.sql
Labels: lgtm, approved, dco-signoff: yes

#102 replace hohconfig with configmap
  agent/cmd/agent/main.go
  agent/pkg/status/controller/apps/subscription_report_sync.go
  agent/pkg/status/controller/apps/subscription_status_sync.go
  agent/pkg/status/controller/config/config_controller.go
  agent/pkg/status/controller/controlinfo/control_info_controller.go
  agent/pkg/status/controller/controller.go
  agent/pkg/status/controller/local_policies/local_policy_sync.go
  agent/pkg/status/controller/localplacement/local_placementrules_sync.go
  agent/pkg/status/controller/managedclusters/clusters_status_sync.go
  agent/pkg/status/controller/placement/placement_decision_sync.go
  agent/pkg/status/controller/placement/placement_rule_sync.go
  agent/pkg/status/controller/placement/placement_sync.go
  agent/pkg/status/controller/policies/policy_status_sync.go
  manager/deploy/cr-examples/hub-of-hubs.open-cluster-management.io_config_cr.yaml
  manager/deploy/crd/hub-of-hubs.open-cluster-management.io_configs.yaml
  manager/pkg/scheme/scheme.go
  manager/pkg/specsyncer/db2transport/syncer/dbsyncer/hoh_config_db_to_transport_syncer.go
  manager/pkg/specsyncer/spec2db/controller/hoh_config_spec_sync.go
  manager/pkg/statussyncer/transport2db/syncer/config/config_controller.go
  manager/pkg/statussyncer/transport2db/syncer/dbsyncer/local_spec_db_syncer.go
  manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer.go
  manager/pkg/statussyncer/transport2db/syncer/syncers.go
  pkg/apis/config/v1/config_types.go
  pkg/apis/config/v1/register.go
  pkg/apis/config/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  test/pkg/e2e/hoh-application_test.go
  test/pkg/e2e/hoh-client_test.go
  test/pkg/utils/shemas.go
  test/setup/e2e_dependencies.sh
  test/setup/hoh/hub-of-hubs-config/cr.yaml
  test/setup/hoh/hub-of-hubs-config/crd.yaml
  test/setup/hoh/hub-of-hubs-config/hoh-config.yaml
  test/setup/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#104 handle hoh resources.
  agent/cmd/agent/main.go
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/bundle/manifests/hubofhubs.open-cluster-management.io_configs.yaml
  operator/config/rbac/role.yaml
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs.open-cluster-management.io_config_crd.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs.open-cluster-management.io_config_crd.yaml
  test/pkg/utils/client.go
Labels: lgtm, approved, dco-signoff: yes

#106 tune db and transport.
  manager/Dockerfile
  manager/cmd/manager/main.go
  manager/deploy/operator.yaml.template
  manager/pkg/specsyncer/db2transport/transport/kafka/producer.go
  manager/pkg/specsyncer/spec2db/controller/hoh_config_spec_sync.go
  manager/pkg/statussyncer/transport2db/db/postgresql/batch/policies_batch_builder.go
  manager/pkg/statussyncer/transport2db/transport/kafka/consumer.go
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#107 clean up hub-of-hubs config.
  agent/deploy/hub-of-hubs-rbac.yaml
  manager/deploy/operator.yaml.template
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/rbac/aggregated_role.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml
  test/setup/hoh/hub-of-hubs-manager.yaml
Labels: lgtm, approved, dco-signoff: yes

#95 Create a new controller to apply the clusterrole and clusterrolebinding by hub-of-hubs-agent
  Makefile
  agent/cmd/agent/main.go
  agent/pkg/controllers/clusterrole_controller.go
  agent/pkg/controllers/clusterrolebinding_controller.go
  agent/pkg/controllers/controllers.go
  agent/pkg/controllers/controllers_integration_test.go
  agent/pkg/controllers/controllers_suite_test.go
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#108 update conditions for hub-of-hubs operator CR.
  operator/pkg/condition/condition.go
  operator/pkg/controllers/hubofhubs/conditions.go
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#110 fix operator aggregated role.
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/rbac/aggregated_role.yaml
  operator/config/rbac/aggregated_role_binding.yaml
Labels: lgtm, approved, dco-signoff: yes

#111 fix code smell
  agent/cmd/agent/main.go
  agent/pkg/applier/applier.go
  agent/pkg/helper/config.go
  agent/pkg/spec/controller/syncers/generic_bundle.go
  agent/pkg/spec/controller/syncers/managed_cluster_label_bundle.go
  agent/pkg/spec/controller/workers/worker_pool.go
  agent/pkg/status/bundle/controlinfo/control_info_bundle.go
  agent/pkg/status/bundle/generic_status_bundle.go
  agent/pkg/status/controller/controlinfo/control_info_controller.go
  agent/pkg/status/controller/controller.go
  agent/pkg/status/controller/generic/generic_status_sync_controller.go
  agent/pkg/status/controller/syncintervals/sync_intervals_controller.go
  agent/pkg/transport/consumer/kafka.go
  agent/pkg/transport/consumer/syncservice.go
  agent/pkg/transport/producer/kafka.go
  agent/pkg/transport/producer/producer.go
  agent/pkg/transport/producer/syncservice.go
  manager/cmd/manager/main.go
  manager/pkg/specsyncer/db2transport/db/db.go
  manager/pkg/specsyncer/db2transport/syncer/statuswatcher/managed_cluster_labels_status_watcher.go
  manager/pkg/specsyncer/db2transport/syncer/syncers.go
  manager/pkg/specsyncer/db2transport/transport/kafka/producer.go
  manager/pkg/specsyncer/db2transport/transport/syncservice/syncservice.go
  manager/pkg/statussyncer/transport2db/syncer/dbsyncer/generic_db_syncer.go
  manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer.go
  manager/pkg/statussyncer/transport2db/syncer/syncers.go
  manager/pkg/statussyncer/transport2db/transport/kafka/consumer.go
  manager/pkg/statussyncer/transport2db/transport/syncservice/sync_service.go
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
  operator/pkg/controllers/leafhub/packagemanifest.go
  operator/pkg/controllers/leafhub/template.go
  operator/pkg/renderer/hoh_renderer.go
  operator/pkg/renderer/renderer.go
  pkg/compressor/gzip_compressor.go
  test/pkg/utils/client.go
  test/pkg/utils/rbac.go
Labels: lgtm, approved, dco-signoff: yes

#109 update hoh lease with hoh agent.
  agent/cmd/agent/main.go
  agent/deploy/hub-of-hubs-rbac.yaml
  agent/pkg/lease/lease.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-deployment.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-role.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-rolebinding.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-serviceaccount.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#113 Add default placement
  Makefile
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/manifests/placement/managedclustersetbinding.yaml
  operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml
Labels: lgtm, approved, dco-signoff: yes

#112 Provide ability to create postgres and kafka for operator local testing
  operator/README.md
  operator/config/samples/kafka/deploy_kafka.sh
  operator/config/samples/kafka/kafka-cluster.yaml
  operator/config/samples/kafka/kafka-operator.yaml
  operator/config/samples/kafka/kafka-topics.yaml
  operator/config/samples/postgres/deploy_postgres.sh
  operator/config/samples/postgres/postgres-cluster/kustomization.yaml
  operator/config/samples/postgres/postgres-cluster/namespace.yaml
  operator/config/samples/postgres/postgres-cluster/postgres-cluster.yaml
  operator/config/samples/postgres/postgres-operator/bases/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
  operator/config/samples/postgres/postgres-operator/bases/crd/kustomization.yaml
  operator/config/samples/postgres/postgres-operator/bases/kustomization.yaml
  operator/config/samples/postgres/postgres-operator/bases/manager/kustomization.yaml
  operator/config/samples/postgres/postgres-operator/bases/manager/manager.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/cluster/kustomization.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/cluster/role.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/cluster/role_binding.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/cluster/service_account.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/namespace/kustomization.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/namespace/role.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/namespace/role_binding.yaml
  operator/config/samples/postgres/postgres-operator/bases/rbac/namespace/service_account.yaml
  operator/config/samples/postgres/postgres-operator/kustomization.yaml
  operator/config/samples/postgres/postgres-operator/namespace.yaml
  operator/pkg/controllers/hubofhubs/config_controller.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/hubofhubs/database/4.authorize.sql
  operator/pkg/controllers/hubofhubs/database/4.trigger.sql
  operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#115 rename hoh operator
  operator/PROJECT
  operator/apis/operator/v1alpha1/groupversion_info.go
  operator/apis/operator/v1alpha1/multiclusterglobalhub_types.go
  operator/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/patches/cainjection_in_configs.yaml
  operator/config/crd/patches/webhook_in_configs.yaml
  operator/config/manifests/bases/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/rbac/config_editor_role.yaml
  operator/config/rbac/config_viewer_role.yaml
  operator/config/rbac/multiclusterglobalhub_editor_role.yaml
  operator/config/rbac/multiclusterglobalhub_viewer_role.yaml
  operator/config/rbac/role.yaml
  operator/config/samples/kustomization.yaml
  operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
  operator/main.go
  operator/pkg/condition/condition.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#114 handle console setup and clean.
  operator/Dockerfile
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/rbac/console_setup_role.yaml
  operator/config/rbac/console_setup_rolebinding.yaml
  operator/config/rbac/kustomization.yaml
  operator/config/rbac/role.yaml
  operator/operator.Dockerfile
  operator/pkg/condition/condition.go
  operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/deployer/hoh_deployer.go
Labels: lgtm, approved, dco-signoff: yes

#117 fix condition set error in mgh delete case.
  operator/pkg/constants/constants.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#119 support console job image customization.
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#118 Fixed the samples kafka and postgre issues
  operator/config/manager/kustomization.yaml
  operator/config/samples/kafka/deploy_kafka.sh
  operator/config/samples/kafka/kafka-operator.yaml
  operator/config/samples/postgres/deploy_postgres.sh
Labels: lgtm, approved, dco-signoff: yes

#120 Skip hub install and console install
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved

#123 add nonk8s authorization for e2e test user
  operator/pkg/controllers/hubofhubs/manifests/rbac/secret-opa-data.yaml
Labels: lgtm, approved

#126 Fix e2e tests
  cicd-scripts/run-prow-e2e-test.sh
Labels: lgtm, approved, dco-signoff: yes

#127 fix console cleanup condition.
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#122 add support for hub-of-hubs operator to watch owned resources
  operator/Dockerfile
  operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/main.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
  operator/pkg/deployer/hoh_deployer.go
Labels: lgtm, approved, dco-signoff: yes

#124 create dynamic client for packagemanifest.
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/packagemanifest.go
Labels: lgtm, approved, dco-signoff: yes

#128 Share kafka and databse setup between operater samples and e2e setup
  cicd-scripts/run-prow-e2e-test.sh
  operator/config/samples/postgres/postgres-cluster/postgres-cluster.yaml
  test/setup/e2e_setup.sh
  test/setup/hoh/components/kafka-community-cluster.yaml
  test/setup/hoh/components/kafka-community-operator.yaml
  test/setup/hoh/kafka_setup.sh
  test/setup/hoh/postgres_setup.sh
  test/setup/hoh_setup.sh
  test/setup/kafka/kafka_setup.sh
  test/setup/postgres/postgres-cluster/kustomization.yaml
  test/setup/postgres/postgres-cluster/namespace.yaml
  test/setup/postgres/postgres-cluster/postgres-cluster.yaml
  test/setup/postgres/postgres-operator/bases/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
  test/setup/postgres/postgres-operator/bases/crd/kustomization.yaml
  test/setup/postgres/postgres-operator/bases/kustomization.yaml
  test/setup/postgres/postgres-operator/bases/manager/kustomization.yaml
  test/setup/postgres/postgres-operator/bases/manager/manager.yaml
  test/setup/postgres/postgres-operator/bases/rbac/cluster/kustomization.yaml
  test/setup/postgres/postgres-operator/bases/rbac/cluster/role.yaml
  test/setup/postgres/postgres-operator/bases/rbac/cluster/role_binding.yaml
  test/setup/postgres/postgres-operator/bases/rbac/cluster/service_account.yaml
  test/setup/postgres/postgres-operator/bases/rbac/namespace/kustomization.yaml
  test/setup/postgres/postgres-operator/bases/rbac/namespace/role.yaml
  test/setup/postgres/postgres-operator/bases/rbac/namespace/role_binding.yaml
  test/setup/postgres/postgres-operator/bases/rbac/namespace/service_account.yaml
  test/setup/postgres/postgres-operator/kustomization.yaml
  test/setup/postgres/postgres-operator/namespace.yaml
  test/setup/postgres/postgres_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#130 Setup local HoH with operator
  Makefile
  test/setup/hoh/components/manager-service-local.yaml
  test/setup/hoh/components/mgh-v1alpha1-cr.yaml
  test/setup/hoh/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#132 Use operator in e2e tests
  cicd-scripts/run-prow-e2e-test.sh
  test/setup/e2e_setup.sh
  test/setup/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#134 update operator API for transport and storage.
  operator/README.md
  operator/apis/operator/v1alpha1/multiclusterglobalhub_types.go
  operator/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/bundle/manifests/multicluster-globalhub-operator.clusterserviceversion.yaml
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/manager/kustomization.yaml
  operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
  operator/config/samples/storage/deploy_postgres.sh
  operator/config/samples/storage/postgres-cluster/kustomization.yaml
  operator/config/samples/storage/postgres-cluster/namespace.yaml
  operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml
  operator/config/samples/storage/postgres-operator/bases/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
  operator/config/samples/storage/postgres-operator/bases/crd/kustomization.yaml
  operator/config/samples/storage/postgres-operator/bases/kustomization.yaml
  operator/config/samples/storage/postgres-operator/bases/manager/kustomization.yaml
  operator/config/samples/storage/postgres-operator/bases/manager/manager.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/cluster/kustomization.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/cluster/role.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/cluster/role_binding.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/cluster/service_account.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/namespace/kustomization.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/namespace/role.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/namespace/role_binding.yaml
  operator/config/samples/storage/postgres-operator/bases/rbac/namespace/service_account.yaml
  operator/config/samples/storage/postgres-operator/kustomization.yaml
  operator/config/samples/storage/postgres-operator/namespace.yaml
  operator/config/samples/transport/deploy_kafka.sh
  operator/config/samples/transport/kafka-cluster.yaml
  operator/config/samples/transport/kafka-operator.yaml
  operator/config/samples/transport/kafka-topics.yaml
  operator/main.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
  test/setup/hoh/components/mgh-v1alpha1-cr.yaml
  test/setup/hoh/hoh_setup.sh
  test/setup/hoh/kafka_setup.sh
  test/setup/hoh/postgres_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#133 Delete the useless e2e setup files
  test/setup/e2e_setup.sh
  test/setup/hoh/multicluster-globalhub-config/hoh-config.yaml
  test/setup/hoh/multicluster-globalhub-kafka-topics.yaml
  test/setup/hoh/multicluster-globalhub-manager.yaml
  test/setup/hoh/multicluster-globalhub-postgres-job.yaml
  test/setup/hoh/multicluster-globalhub-rbac/operator.yaml
  test/setup/hoh/multicluster-globalhub-rbac/secret/data.json
  test/setup/hoh/multicluster-globalhub-rbac/secret/opa_authorization.rego
  test/setup/hoh/multicluster-globalhub-rbac/secret/role_bindings.yaml
Labels: lgtm, approved, dco-signoff: yes

#137 Update the readme
  README.md
  doc/architecture/multicluster-globalhub-arch.png
Labels: lgtm, approved, dco-signoff: yes

#138 add retry for managedcluster retrieval in e2e.
  test/pkg/e2e/hoh-application_test.go
  test/pkg/e2e/hoh-policy_test.go
Labels: lgtm, approved, dco-signoff: yes

#136 rename hub-of-hubs to multicluster-globalhub.
  operator/README.md
  operator/bundle/manifests/multicluster-globalhub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-globalhub-operator.clusterserviceversion.yaml
  operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
  operator/pkg/condition/condition.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-multicluster-globalhub-agent-applier.yaml
  operator/pkg/renderer/hoh_renderer.go
Labels: lgtm, approved, dco-signoff: yes

#139 Fix the vulnerabilities reported by dependabot
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#143 rename to global-hub
  agent/deploy/multicluster-global-hub-agent.yaml
  agent/deploy/multicluster-global-hub-rbac.yaml
  doc/architecture/multicluster-global-hub-arch.png
  operator/bundle/manifests/multicluster-global-hub-operator-manager-config_v1_configmap.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-clusterrolebinding.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-configmap.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-namespace.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-serviceaccount.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/multicluster-global-hub-agent-deployment.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/multicluster-global-hub-agent-role.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/multicluster-global-hub-agent-rolebinding.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/multicluster-global-hub-agent-serviceaccount.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-multicluster-global-hub-agent-applier.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-clusterrolebinding.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-configmap.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-deployment.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-namespace.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-serviceaccount.yaml
Labels: lgtm, approved, dco-signoff: yes

#140 clear sample pg users and kafka ca file
  Makefile
  operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml
  operator/config/samples/transport/deploy_kafka.sh
Labels: lgtm, approved

#144 fixed a typo in old release notes
  release-notes/v0.4.0.md
Labels: lgtm, approved, dco-signoff: no

#147 added license badge to README
  README.md
Labels: lgtm, approved, dco-signoff: yes

#149 added go reference badge
  README.md
Labels: lgtm, approved, dco-signoff: yes

#145 Labels/Annotations/Finalizers
  Makefile
  agent/pkg/controllers/clusterrole_controller.go
  agent/pkg/controllers/clusterrolebinding_controller.go
  agent/pkg/status/bundle/grc/complete_compliance_status_bundle.go
  agent/pkg/status/controller/generic/generic_status_sync_controller.go
  agent/pkg/status/controller/managedclusters/clusters_status_sync.go
  agent/pkg/status/controller/placement/placement_rule_sync.go
  doc/reserved_names/README.md
  manager/cmd/manager/main.go
  manager/pkg/specsyncer/db2transport/db/postgresql/postgresql.go
  manager/pkg/specsyncer/spec2db/controller/application_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/channel_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/generic_spec_to_db_reconciler.go
  manager/pkg/specsyncer/spec2db/controller/hoh_config_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/managedclusterset_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/placement_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/placementbinding_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/placementrule_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/policy_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/subscription_spec_sync.go
  manager/pkg/statussyncer/db2status/dbsyncer/placement_syncer.go
  manager/pkg/statussyncer/status/controller/placementbinding_controller.go
  manager/pkg/statussyncer/transport2db/bundle/delta_compliance_status_bundle.go
  manager/pkg/statussyncer/transport2db/db/postgresql/batch/policies_batch_builder.go
  manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer.go
  manager/pkg/statussyncer/transport2db/transport/kafka/committer.go
  operator/main.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
  pkg/constants/constants.go
  test/resources/policy/local-enforce-limitrange-policy.yaml
  test/resources/policy/local-inform-limitrange-policy.yaml
  test/setup/e2e_setup.sh
  test/setup/hoh/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#148 add contributing section
  README.md
Labels: lgtm, approved, dco-signoff: yes

#142 support image overrides.
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
  operator/main.go
  operator/pkg/config/hypershift_config.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/config/multiclusterglobalhub_config_test.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
  test/setup/hoh/components/mgh-images-config.yaml
  test/setup/hoh/components/mgh-v1alpha1-cr.yaml
  test/setup/hoh/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#146 Reduce the e2e OLM installation time
  test/setup/common.sh
  test/setup/e2e_dependencies.sh
Labels: lgtm, approved, dco-signoff: yes

#151 Try to fix the sonarcloud error
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#153 Fix sonarcloud issue again
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#150 update bundle.
  operator/Makefile
  operator/bundle.Dockerfile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/metadata/annotations.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#152 overwrite the e2e leafhub label for mgh operator
  test/setup/e2e_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#156 Clean up the hub-of-hubs and remove unused manifests
  agent/deploy/multicluster-global-hub-agent.yaml
  agent/deploy/multicluster-global-hub-rbac.yaml
  development.md
  doc/hypershift/README.md
  doc/hypershift/hypershift-regionalhub-import-cluster.md
  manager/cmd/manager/main.go
  manager/deploy/operator.yaml.template
Labels: lgtm, approved, dco-signoff: yes

#154 update operator install mode.
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#158 update to use 0.5.0 instead of latest tag
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
Labels: lgtm, approved, dco-signoff: yes

#157 replace deprecated package ioutil with io and os
  test/pkg/e2e/hoh-client_test.go
  test/pkg/e2e/hoh-cluster_test.go
  test/pkg/e2e/hoh-e2e-test_suite_test.go
  test/pkg/e2e/hoh-label_test.go
  test/pkg/e2e/hoh-policy_test.go
Labels: lgtm, approved, dco-signoff: yes

#155 set mgh-images-config with image tags for local testing
  test/setup/hoh/components/mgh-images-config.yaml
  test/setup/hoh/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#160 update operator CR kind.
  operator/PROJECT
  operator/apis/operator/v1alpha1/multiclusterglobalhub_types.go
  operator/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
  operator/main.go
  operator/pkg/condition/condition.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/config/multiclusterglobalhub_config_test.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/database.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
  test/setup/hoh/components/mgh-v1alpha1-cr.yaml
Labels: lgtm, approved, dco-signoff: yes

#161 Init resources
  agent/cmd/agent/main.go
  agent/pkg/controllers/clusterrole_controller.go
  agent/pkg/controllers/clusterrolebinding_controller.go
  agent/pkg/controllers/controllers.go
  agent/pkg/controllers/controllers_integration_test.go
  operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml
Labels: lgtm, approved, dco-signoff: yes

#162 support installation in any namespace.
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/role.yaml
  operator/config/samples/storage/deploy_postgres.sh
  operator/config/samples/transport/deploy_kafka.sh
  operator/pkg/condition/condition.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/clusterrolebinding.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/configmap-ca-bundle.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/ingress.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/role.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/rolebinding.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/service.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/serviceaccount.yaml
  operator/pkg/controllers/hubofhubs/manifests/placement/managedclustersetbinding.yaml
  operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml
  operator/pkg/controllers/hubofhubs/manifests/rbac/deployment.yaml
  operator/pkg/controllers/hubofhubs/manifests/rbac/networkpolicy.yaml
  operator/pkg/controllers/hubofhubs/manifests/rbac/secret-opa-data.yaml
  operator/pkg/controllers/hubofhubs/manifests/rbac/service.yaml
  operator/pkg/controllers/hubofhubs/manifests/rbac/serviceaccount.yaml
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/addon.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#163 use the default control-runtime default values
  agent/cmd/agent/main.go
Labels: lgtm, approved, dco-signoff: yes

#164 Correct the configmap name
  operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
Labels: lgtm, approved, dco-signoff: yes

#165 Rename hoh to mgh for some resources
  agent/cmd/agent/main.go
  agent/pkg/spec/controller/syncers/managed_cluster_label_bundle.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-configmap.yaml
  operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-namespace.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-configmap.yaml
  operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-namespace.yaml
  pkg/constants/constants.go
  test/pkg/e2e/hoh-client_test.go
Labels: lgtm, approved, dco-signoff: yes

#166 add check sum for operator image.
  operator/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#167 add missing permission for operator.
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/pkg/controllers/leafhub/leafhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#159 delete mgh CR resources from manager
  manager/Dockerfile
  manager/scripts/prestop.sh
  operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#168 delete mgh CR resource from agent
  operator/pkg/controllers/hubofhubs/manifests/placement/managedclustersetbinding.yaml
  operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml
Labels: lgtm, approved, dco-signoff: yes

#170 fix hosting cluster reconcile triggered by manifestwork changes.
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  operator/pkg/controllers/leafhub/leafhub_controller.go
  operator/pkg/controllers/leafhub/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#174 Revert "delete mgh CR resources from manager"
  manager/Dockerfile
  manager/scripts/prestop.sh
  operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
  operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#175 Prevent local resources from being propagated to regional cluster
  manager/pkg/specsyncer/spec2db/controller/managedclusterset_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go
  manager/pkg/specsyncer/spec2db/controller/placement_spec_sync.go
Labels: lgtm, approved, dco-signoff: yes

#179 update readme.
  README.md
  operator/README.md
Labels: lgtm, approved, dco-signoff: yes

#181 Enhance tests
  Makefile
  test/pkg/e2e/hoh-application_test.go
  test/pkg/e2e/hoh-cluster_test.go
  test/pkg/e2e/hoh-e2e-test_suite_test.go
  test/pkg/e2e/hoh-label_test.go
  test/pkg/e2e/hoh-local-policy_test.go
  test/pkg/e2e/hoh-policy_test.go
  test/setup/hoh/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#180 prune application finalizer from global cluster
  operator/bundle.Dockerfile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/metadata/annotations.yaml
  operator/config/rbac/role.yaml
  operator/main.go
  operator/pkg/controllers/hubofhubs/finalizer.go
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
  test/setup/hoh/hoh_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#184 add missing watch for resources created but not owned by operator
  operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#182 fix e2e failures temporarily
  manager/pkg/nonk8sapi/non_k8s_api.go
  manager/pkg/nonk8sapi/policies/list_status.go
  test/pkg/e2e/hoh-application_test.go
  test/pkg/e2e/hoh-policy_test.go
  test/pkg/utils/client.go
  test/resources/app/app-helloworld-appsub.yaml
Labels: lgtm, approved, dco-signoff: yes
