Repository stolostron/multicluster-global-hub, pull requests merged in 2024-12, with the labels that each got.

#1252 fix manager do not recreted after delete manager deploy
  operator/pkg/config/status.go
  operator/pkg/config/storage_config.go
  operator/pkg/config/transport_config.go
  operator/pkg/controllers/acm/resources.go
  operator/pkg/controllers/agent/addon_manager.go
  operator/pkg/controllers/agent/default_agent_controller.go
  operator/pkg/controllers/agent/hosted_agent_controller.go
  operator/pkg/controllers/backup/backup_reconcile.go
  operator/pkg/controllers/backup/backup_start.go
  operator/pkg/controllers/grafana/grafana_reconciler.go
  operator/pkg/controllers/inventory/inventory_reconciler.go
  operator/pkg/controllers/managedhub/managedhub_controller.go
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/storage/storage_reconciler.go
  operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
  operator/pkg/controllers/transporter/transport_reconciler.go
  operator/pkg/controllers/webhook/webhook_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1250 :sparkles: Use Kafka KRaft
  go.mod
  go.sum
  operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
  operator/api/operator/v1alpha4/zz_generated.deepcopy.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/pkg/constants/constants.go
  operator/pkg/controllers/grafana/manifests/acm-global-strimzi-zookeeper.yaml
  operator/pkg/controllers/grafana/manifests/deployment.yaml
  operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka-node-pool.yaml
  operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka.yaml
  operator/pkg/controllers/transporter/protocol/manifests/metrics.yaml
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter_test.go
  operator/pkg/utils/utils.go
  operator/pkg/utils/utils_test.go
  samples/config/confluent_config.go
  samples/config/sarama_config.go
  test/e2e/suite_test.go
  test/integration/operator/controllers/manager_test.go
  test/integration/operator/controllers/transporter_test.go
  test/manifest/crd/0000_05_kafka.strimzi.io_kafkanodepools.crd.yaml
  test/manifest/crd/0000_05_kafka.strimzi.io_kafkas.crd.yaml
  test/manifest/crd/0000_05_kafka.strimzi.io_kafkatopics.crd.yaml
  test/manifest/crd/0000_05_kafka.strimzi.io_kafkausers.crd.yaml
  test/manifest/kafka/kafka-cluster/kafka-cluster.yaml
  test/script/e2e_kafka.sh
  test/script/e2e_run.sh
  test/script/e2e_run_byo.sh
  test/script/event_exporter_kafka.sh
  test/script/kessel_e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1260 :seedling: Clean the resource when the addon is not found
  manager/pkg/processes/hubmanagement/hub_addon_controller.go
  manager/pkg/processes/hubmanagement/hub_addon_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#1261 :seedling: Lower the log level for the producer error "brokers are down"
  pkg/transport/producer/generic_producer.go
Labels: lgtm, approved, dco-signoff: yes

#1257 :bug: Resync the managed hub resources upon manager startup
  agent/pkg/spec/dispatcher.go
  manager/pkg/processes/hubmanagement/hub_management.go
  test/integration/manager/spec/db2transport_test.go
  test/integration/manager/spec/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1262 fix metric lost
  manager/pkg/processes/cronjob/scheduler.go
  test/integration/manager/controller/scheduler_test.go
Labels: lgtm, approved, dco-signoff: yes

#1259 :sparkles: Put klusterletaddonconfig into managedclustermigration CR
  agent/pkg/configs/scheme.go
  agent/pkg/controllers/init_controller.go
  agent/pkg/spec/spec.go
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  manager/pkg/configs/scheme.go
  manager/pkg/controllers/migration_controller.go
  manager/pkg/status/conflator/conflation_priority.go
  manager/pkg/status/handlers/handlers.go
  manager/pkg/status/handlers/managedcluster/klusterlet_addon_config_handler.go
  manager/pkg/status/handlers/managedcluster/klusterlet_addon_config_handler_test.go
  manager/pkg/status/status.go
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  pkg/bundle/event/managedcluster_migration_event.go
  pkg/constants/constants.go
  pkg/enum/event_type.go
  pkg/transport/controller/controller.go
  test/integration/agent/spec/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1270 print database error
  operator/pkg/controllers/storage/storage_reconciler.go
Labels: lgtm, approved, dco-signoff: yes

#1263 fix watch resources in each controller
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/controllers/acm/resources.go
  operator/pkg/controllers/agent/addon_manager.go
  operator/pkg/controllers/agent/default_agent_controller.go
  operator/pkg/controllers/agent/hosted_agent_controller.go
  operator/pkg/controllers/backup/backup_start.go
  operator/pkg/controllers/grafana/grafana_reconciler.go
  operator/pkg/controllers/inventory/inventory_reconciler.go
  operator/pkg/controllers/managedhub/managedhub_controller.go
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/storage/storage_reconciler.go
  operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
  operator/pkg/controllers/transporter/transport_reconciler.go
  operator/pkg/controllers/webhook/webhook_controller.go
  test/integration/operator/controllers/grafana_test.go
  test/integration/operator/controllers/inventory_test.go
  test/integration/operator/controllers/storage_test.go
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1271 :seedling: Add git commit to downstream images
  agent/Containerfile.operator
  manager/Containerfile.operator
  operator/Containerfile.operator
Labels: lgtm, approved, dco-signoff: yes

#1264 :sparkles: Upgrade the postgres from 13 to 16
  doc/how_global_hub_works.md
  doc/simulation/backup_restore/README.md
  doc/simulation/inspector/README.md
  doc/simulation/inspector/src/counter.py
  doc/simulation/inspector/src/cpu_usage.py
  doc/simulation/inspector/src/memory_usage.py
  doc/simulation/local-policies/README.md
  doc/simulation/scenario/Scenario5: postgres_metrics.md
  doc/troubleshooting.md
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/config/status.go
  operator/pkg/controllers/grafana/manifests/acm-global-postgres.yaml
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/manager/manifests/deployment.yaml
  operator/pkg/controllers/manager/manifests/storage-config-secret.yaml
  operator/pkg/controllers/meta.go
  operator/pkg/controllers/storage/manifests.sts/grafana-postgres-alert.yaml
  operator/pkg/controllers/storage/manifests.sts/grafana-service-monitor.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-ca-configmap.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-config-configmap.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-init-configmap.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-secret.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-service.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-serviceaccount.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-statefulset.yaml
  operator/pkg/controllers/storage/postgres_statefulset.go
  operator/pkg/controllers/storage/storage_reconciler.go
  pkg/constants/constants.go
  test/e2e/suite_test.go
  test/integration/operator/controllers/inventory_test.go
  test/integration/operator/controllers/storage_test.go
Labels: lgtm, approved, dco-signoff: yes

#1272 fix dashboard - postgres database has no data
  operator/pkg/controllers/storage/manifests.sts/grafana-service-monitor.yaml
  operator/pkg/controllers/storage/postgres_statefulset.go
Labels: lgtm, approved, dco-signoff: yes

#1281 Fix CVE-2024-45337
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1282 Fix CVE-2024-45337
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1280 :bug: integration test error for localpolicy event filter
  test/integration/agent/status/localpolicy_event_test.go
Labels: lgtm, approved, dco-signoff: yes

#1279 Use Containerfile.operator in Konflux build
  .tekton/multicluster-global-hub-agent-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-agent-globalhub-1-4-push.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-4-push.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-4-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1283 :seedling: Bump go version to 1.23.4
  .github/workflows/e2e.yml
  .github/workflows/go.yml
  agent/Containerfile.operator
  go.mod
  go.sum
  manager/Containerfile.operator
  operator/Containerfile.operator
  pkg/transport/config/saram_config.go
  pkg/transport/consumer/sarama_consumer.go
  pkg/transport/consumer/sarama_consumer_test.go
  samples/README.md
  samples/cloudevent/receiver/main.go
  samples/cloudevent/sender/main.go
  samples/config/sarama_config.go
  samples/kafka/saram_consumer/main.go
  samples/kafka/saram_producer/main.go
  test/e2e/agent_test.go
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1286 Revert ":seedling: Bump go version to 1.23.4"
  .github/workflows/e2e.yml
  .github/workflows/go.yml
  agent/Containerfile.operator
  go.mod
  go.sum
  manager/Containerfile.operator
  operator/Containerfile.operator
  pkg/transport/config/saram_config.go
  pkg/transport/consumer/sarama_consumer.go
  pkg/transport/consumer/sarama_consumer_test.go
  samples/README.md
  samples/cloudevent/receiver/main.go
  samples/cloudevent/sender/main.go
  samples/config/sarama_config.go
  samples/kafka/saram_consumer/main.go
  samples/kafka/saram_producer/main.go
  test/e2e/agent_test.go
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: no

#1289 remove duplicate pannel in kafkadashboard
  operator/pkg/controllers/grafana/manifests/acm-global-strimzi-kafka.yaml
Labels: lgtm, approved, dco-signoff: yes

#1290 :bug: Get clusterId from managedcluster
  agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller.go
  agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller_test.go
  operator/pkg/controllers/agent/addon_manager.go
  samples/inventory/requester/global_hub.go
  samples/inventory/requester/managed_hub.go
  test/e2e/kessel/cluster_test.go
Labels: lgtm, approved, dco-signoff: yes

#1287 :bug: not received event for the agent status integartion test
  agent/pkg/status/filter/time_filter.go
  test/integration/agent/status/localpolicy_event_test.go
Labels: lgtm, approved, dco-signoff: yes

#1284 handle upgrade kafka from zookeeper to kraft
  doc/reserved_names/README.md
  operator/pkg/controllers/inventory/inventory_reconciler.go
  operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka-node-pool.yaml
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  pkg/constants/constants.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/transport/kafka_config.go
Labels: lgtm, approved, dco-signoff: yes

#1293 :bug: Fix the failure of integration test
  operator/pkg/config/condition_test.go
  operator/pkg/controllers/backup/suite_test.go
  operator/pkg/deployer/hoh_deployer_suite_test.go
  pkg/jobs/jobs_suite_test.go
  test/integration/agent/controller/suite_test.go
  test/integration/agent/spec/suite_test.go
  test/integration/agent/status/suite_test.go
  test/integration/manager/controller/suite_test.go
  test/integration/manager/spec/suite_test.go
  test/integration/manager/status/suite_test.go
  test/integration/manager/webhook/admission_suite_test.go
  test/integration/operator/controllers/agent/hosted_managedhub/suite_test.go
  test/integration/operator/controllers/agent/suite_test.go
  test/integration/operator/controllers/suite_test.go
  test/integration/operator/suite_test.go
  test/integration/operator/webhook/admission_suite_test.go
Labels: approved, dco-signoff: yes

#1294 :bug: Fix integration
  operator/pkg/config/condition_test.go
  operator/pkg/controllers/backup/suite_test.go
  operator/pkg/controllers/crd/crd_controller_test.go
  operator/pkg/controllers/hubofhubs/controller_test.go
  operator/pkg/deployer/hoh_deployer_suite_test.go
  pkg/jobs/jobs_suite_test.go
  test/integration/agent/controller/suite_test.go
  test/integration/agent/spec/suite_test.go
  test/integration/agent/status/suite_test.go
  test/integration/manager/controller/suite_test.go
  test/integration/manager/spec/suite_test.go
  test/integration/manager/status/suite_test.go
  test/integration/manager/webhook/admission_suite_test.go
  test/integration/operator/addons/suite_test.go
  test/integration/operator/agent/suite_test.go
  test/integration/operator/hubofhubs/suite_test.go
  test/integration/operator/webhook/admission_suite_test.go
  test/manifest/kafka/kafka-cluster/kafka-cluster.yaml
Labels: lgtm, approved, dco-signoff: yes

#1288 fix error when delete mgh then recreate it
  operator/pkg/config/storage_config.go
  operator/pkg/config/transport_config.go
  operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1291 :bug: Get clusterId from managedcluster
  agent/pkg/status/controller/managedclusters/k8s_cluster_test.go
  agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go
  agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer_test.go
  samples/inventory/requester/global_hub.go
  samples/inventory/requester/managed_hub.go
Labels: lgtm, approved, dco-signoff: yes

#1292 :seedling: Bump version to 1.3.2
  operator/Makefile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1285 :seedling: Restore the history and event tables after upgrading GH to 1.4.0
  doc/troubleshooting.md
  doc/upgrade/cleanup_legacy_postgres.sh
  doc/upgrade/restore_event_tables.sh
  doc/upgrade/restore_history_tables.sh
  doc/upgrade/upgrade_to_globalhub_1.4.0.md
Labels: lgtm, approved, dco-signoff: yes

#1300 :bug: remove relatedImages
  operator/Makefile
  operator/bundle/konflux-patch.sh
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1304 fix deployment always update
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
  operator/pkg/controllers/agent/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml
  operator/pkg/controllers/agent/manifests/templates/hubcluster/hubcluster-mch.yaml
  operator/pkg/controllers/grafana/manifests/deployment.yaml
  operator/pkg/controllers/inventory/manifests/deployment.yaml
  operator/pkg/controllers/manager/manifests/deployment.yaml
  operator/pkg/controllers/storage/manifests.sts/postgres-statefulset.yaml
  operator/pkg/renderer/testdata/app/nginx-deployment.yaml
  operator/pkg/renderer/testdata/output/all-nginx.golden.yaml
  operator/pkg/renderer/testdata/output/all.golden.yaml
  operator/pkg/renderer/testdata/output/default.golden.yaml
  operator/pkg/renderer/testdata/output/external.golden.yaml
  operator/pkg/renderer/testdata/output/ha.golden.yaml
Labels: lgtm, approved, dco-signoff: yes

#1306 Remove redundant annotations
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1305 Bump to 1.23.2
  .github/workflows/e2e.yml
  agent/Containerfile.agent
  go.mod
  go.sum
  manager/Containerfile.manager
  operator/Containerfile.operator
  pkg/transport/config/saram_config.go
  pkg/transport/consumer/sarama_consumer.go
  pkg/transport/consumer/sarama_consumer_test.go
  samples/README.md
  samples/cloudevent/receiver/main.go
  samples/cloudevent/sender/main.go
  samples/config/sarama_config.go
  samples/kafka/saram_consumer/main.go
  samples/kafka/saram_producer/main.go
  test/e2e/agent_test.go
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1303 fix some issue about upgrade
  operator/pkg/controllers/agent/addon_manager.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  pkg/constants/constants.go
  test/integration/operator/controllers/agent/suite_test.go
Labels: lgtm, approved, dco-signoff: yes
