Repository stolostron/multicluster-global-hub, pull requests merged in 2024-09, with the labels that each got.

#1068 Add e2e for deploying global hub without ACM
  .github/workflows/e2e.yml
  go.mod
  go.sum
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/role.yaml
  operator/pkg/constants/constants.go
  operator/pkg/controllers/agent/addon_installer.go
  operator/pkg/controllers/hubofhubs/controller.go
  operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
  operator/pkg/controllers/hubofhubs/prune/prune_reconciler_test.go
  operator/pkg/controllers/hubofhubs/storage/manifests.sts/init-configmap.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka-node-pool.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_kafka_controller.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter_test.go
  operator/pkg/utils/utils.go
  test/Makefile
  test/integration/operator/hubofhubs/controller_test.go
  test/integration/operator/hubofhubs/inventory_test.go
  test/kessel_e2e/setup/e2e_setup.sh
  test/kessel_e2e/setup/service-ca-crds/clusteroperators-crd.yaml
  test/kessel_e2e/setup/service-ca-crds/servicecas-crd.yaml
  test/kessel_e2e/setup/service-ca/00_roles.yaml
  test/kessel_e2e/setup/service-ca/01_namespace.yaml
  test/kessel_e2e/setup/service-ca/02_service.yaml
  test/kessel_e2e/setup/service-ca/03_cm.yaml
  test/kessel_e2e/setup/service-ca/03_operator.cr.yaml
  test/kessel_e2e/setup/service-ca/04_sa.yaml
  test/kessel_e2e/setup/service-ca/05_deploy.yaml
  test/kessel_e2e/setup/service-ca/07_clusteroperator.yaml
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1081 fix issue about importing hosted hub
  operator/pkg/controllers/addons/addons_controller.go
  operator/pkg/controllers/addons/addons_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#1082 :bug: Fix agent can't connect to the kafka cluster
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-kafka-certs-secret.yaml
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-kafka-cluster-ca-cert.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/byo_transporter.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_kafka_controller.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  pkg/transport/config/confluent_config.go
  pkg/transport/consumer/generic_consumer.go
  pkg/transport/controller/controller.go
  pkg/transport/producer/generic_producer.go
  test/integration/operator/agent/addon_deploy_test.go
Labels: lgtm, approved, dco-signoff: yes

#1084 :bug: Use stolostron grafana image
  operator/pkg/certificates/cert_controller.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/config/storage_config.go
  operator/pkg/controllers/hubofhubs/inventory/inventory_reconciler.go
Labels: lgtm, approved, dco-signoff: yes

#1085 :memo: Use KRaft for BYO e2e
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  test/manifest/kafka/kafka-cluster/kafka-cluster.yaml
  test/script/e2e_kafka.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1086 :seedling: Remove the kafka certs for the manager and agent
  operator/pkg/controllers/agent/addon_controller_manifests.go
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
  operator/pkg/controllers/agent/manifests/templates/hostedagent/multicluster-global-hub-agent-kafka-certs-secret.yaml
  operator/pkg/controllers/agent/manifests/templates/hostedagent/multicluster-global-hub-agent-kafka-cluster-ca-cert.yaml
  operator/pkg/controllers/agent/manifests/templates/hostedagent/multicluster-global-hub-agent-transport-config-secret.yaml
  operator/pkg/controllers/hubofhubs/manager/manager_reconciler.go
  operator/pkg/controllers/hubofhubs/manager/manifests/kafka-certs-secret.yaml
  pkg/transport/type.go
  test/integration/operator/agent/addon_deploy_test.go
Labels: lgtm, approved, dco-signoff: yes

#1067 MGMT-18592: Add security alerts dashboard
  doc/reserved_names/README.md
  manager/pkg/statussyncer/conflator/conflation_priority.go
  manager/pkg/statussyncer/syncers.go
  manager/pkg/statussyncer/syncers/security_alert_counts_handler.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/grafana/grafana_reconciler.go
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-security-alert-counts.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/deployment.yaml
  operator/pkg/controllers/hubofhubs/storage/database/1.schemas.sql
  operator/pkg/controllers/hubofhubs/storage/database/2.tables.sql
  operator/pkg/controllers/hubofhubs/storage/database/5.privileges.sql
  pkg/database/constants.go
  pkg/database/models/security.go
  pkg/enum/event_type.go
  pkg/wire/models/security.go
  test/integration/manager/status/security_alert_counts_handler_test.go
Labels: lgtm, approved, dco-signoff: yes

#1078 run e2e using default middleware and byo middleware
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  test/Makefile
  test/e2e/backup_test.go
  test/e2e/suite_test.go
  test/manifest/crd/0000_03_config-operator_01_proxies.crd.yaml
  test/script/e2e_clean_globalhub.sh
  test/script/e2e_kafka.sh
  test/script/e2e_postgres.sh
  test/script/e2e_run.sh
  test/script/e2e_run_byo.sh
  test/script/e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1088 :sparkles: Wire inventory to Kafka
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/pkg/constants/constants.go
  operator/pkg/controllers/hubofhubs/inventory/inventory_reconciler.go
  operator/pkg/controllers/hubofhubs/inventory/manifests/deployment.yaml
  operator/pkg/controllers/hubofhubs/inventory/manifests/kafka-certs.yaml
  operator/pkg/controllers/hubofhubs/inventory/manifests/secret.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  test/kessel_e2e/setup/e2e_setup.sh
Labels: lgtm, approved, dco-signoff: yes

#1089 [doc] remove hosted import
  doc/dev-preview.md
  doc/import_hosted_cluster.png
Labels: lgtm, approved, dco-signoff: yes

#1093 change compliance keyword to violiation
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-adhoc-investigation.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-managedclusters.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-offending-clusters.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-offending-policies.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-overview.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-whats-changed-clusters.yaml
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-whats-changed-policies.yaml
Labels: lgtm, approved, dco-signoff: yes

#1095 :bug: fix postgres dashboard format error
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-postgres.yaml
Labels: lgtm, approved, dco-signoff: yes

#1096 :bug: Create inventory topic
  operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka-topic.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka-user.yaml
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
Labels: lgtm, approved, dco-signoff: yes

#1079 :sparkles: Support the agent to deploy in a standalone mode
  agent/cmd/agent/main.go
  agent/cmd/agent/main_test.go
  agent/pkg/config/agent_config.go
  agent/pkg/controllers/crd_controller.go
  agent/pkg/controllers/crd_controller_test.go
  agent/pkg/status/controller/controller.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/transport/producer/generic_producer.go
  pkg/transport/producer/generic_producer_test.go
  pkg/transport/type.go
  samples/cloudevent/receiver/main.go
  samples/cloudevent/sender/main.go
  samples/config/sarama_config.go
  test/Makefile
  test/e2e/agent_test.go
  test/manifest/standalone-agent/generate_transport_config.sh
  test/manifest/standalone-agent/standalone-agent-resources.yaml
  test/manifest/standalone-agent/workload/clusterrole.yaml
  test/manifest/standalone-agent/workload/clusterrolebinding.yaml
  test/manifest/standalone-agent/workload/configmap.yaml
  test/manifest/standalone-agent/workload/deployment.yaml
  test/manifest/standalone-agent/workload/namespace.yaml
  test/manifest/standalone-agent/workload/serviceaccount.yaml
  test/script/e2e_kafka.sh
  test/script/e2e_log.sh
  test/script/e2e_postgres.sh
  test/script/e2e_prow.sh
  test/script/e2e_run.sh
  test/script/e2e_run_byo.sh
  test/script/e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1097 Only watch metadata of CRDs in agent
  agent/pkg/controllers/crd_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1092 ACM-14143: Document how to enable StackRox integration
  doc/dev-preview.md
  doc/images/rhacs-central-dashboard.png
  doc/images/rhacs-create-api-token-dialog.png
  doc/images/rhacs-create-api-token-result.png
  doc/images/rhacs-global-hub-dashboard.png
Labels: lgtm, approved, dco-signoff: yes

#1100 Update pull request template to remind the tests
  .github/pull_request_template.md
Labels: lgtm, approved, dco-signoff: yes

#1099 :bug: Remove the database condition test from integration
  test/integration/operator/hubofhubs/storage_test.go
Labels: lgtm, approved, dco-signoff: yes

#1101 :bug: Fix the issue of event loss caused by time filtering.
  agent/pkg/status/controller/filter/time_filter.go
  agent/pkg/status/controller/filter/time_filter_test.go
  agent/pkg/status/controller/policies/status_event_emitter.go
  test/integration/agent/status/localpolicy_event_test.go
Labels: lgtm, approved, dco-signoff: yes

#1098 :bug: e2e kind cluster creating error
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1091 MGMT-18597: Poll Stackrox Central for violation counts and push it to Kafka
  agent/cmd/agent/main.go
  agent/pkg/clients/stackrox_client.go
  agent/pkg/clients/stackrox_client_test.go
  agent/pkg/clients/suite_test.go
  agent/pkg/config/agent_config.go
  agent/pkg/controllers/crd_controller.go
  agent/pkg/controllers/crd_controller_test.go
  agent/pkg/status/controller/security/common.go
  agent/pkg/status/controller/security/stackrox_alert_count_summary.go
  agent/pkg/status/controller/security/stackrox_controller.go
  agent/pkg/status/controller/security/stackrox_requests.go
  agent/pkg/status/controller/security/stackrox_syncer.go
  agent/pkg/status/controller/security/stackrox_syncer_test.go
  agent/pkg/status/controller/security/suite_test.go
  go.mod
  go.sum
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/config/multiclusterglobalhub_config_test.go
  operator/pkg/constants/constants.go
  operator/pkg/controllers/agent/addon_controller_manifests.go
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
  pkg/transport/transport_mocks.go
Labels: lgtm, approved, dco-signoff: yes

#1106 ACM-14143: Fix section levels in StackRox integration doc
  doc/dev-preview.md
Labels: lgtm, approved, dco-signoff: yes

#1102 :sparkles: Introduce managedclustermigration api
  go.mod
  go.sum
  operator/PROJECT
  operator/api/migration/v1alpha1/groupversion_info.go
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/api/migration/v1alpha1/zz_generated.deepcopy.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator-manager-config_v1_configmap.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/config/crd/kustomization.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/pkg/controllers/hubofhubs/manager/manifests/global-hub-kafka-topic.yaml
  operator/pkg/controllers/hubofhubs/manager/manifests/global-hub-kafka-user.yaml
Labels: lgtm, approved, dco-signoff: yes

#1105 :sparkles: Add 'source' column to security violations dashboard
  agent/pkg/status/controller/security/stackrox_alert_count_summary.go
  agent/pkg/status/controller/security/stackrox_syncer.go
  agent/pkg/status/controller/security/stackrox_syncer_test.go
  manager/pkg/statussyncer/syncers/security_alert_counts_handler.go
  operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-security-alert-counts.yaml
  operator/pkg/controllers/hubofhubs/storage/database/2.tables.sql
  operator/pkg/controllers/hubofhubs/storage/upgrade/1.upgrade.sql
  pkg/database/models/security.go
  pkg/wire/models/security.go
  test/integration/manager/status/security_alert_counts_handler_test.go
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1107 fix install hosted in other ns
  operator/pkg/controllers/hubofhubs/webhook/manifests/addondeploymentconfig.yaml
Labels: lgtm, approved, dco-signoff: yes

#1113 bump the addon framework to v0.10.0
  go.mod
  go.sum
  operator/pkg/controllers/agent/addon_installer.go
Labels: lgtm, approved, dco-signoff: yes

#1104 :sparkles: Enable the agent to send event to inventory server
  agent/cmd/agent/main.go
  agent/cmd/agent/main_test.go
  agent/pkg/config/scheme.go
  agent/pkg/status/controller/controller.go
  agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go
  agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer_test.go
  doc/event-exporter/templates/clusterrole.yaml
  go.mod
  go.sum
  manager/cmd/manager/main.go
  operator/pkg/controllers/agent/addon_installer.go
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/agent/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml
  operator/pkg/controllers/hubofhubs/manager/manifests/deployment.yaml
  pkg/enum/event_type.go
  pkg/transport/config/rest_config.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/transport/inventory/client/client.go
  pkg/transport/inventory/client/client_test.go
  pkg/transport/inventory/transfer/k8s_cluster.go
  pkg/transport/inventory/transfer/k8s_cluster_test.go
  pkg/transport/producer/generic_producer.go
  samples/config/confluent_config.go
  samples/config/transport_secret.go
  samples/inventory/consumer/main.go
  samples/inventory/producer/main.go
  test/integration/operator/agent/addon_registry_test.go
  test/manifest/crd/0000_06_internal.open-cluster-management.io_managedclusterinfos.crd.yaml
  test/manifest/crd/clusterversion.crd.yaml
  test/script/e2e_clean_globalhub.sh
  test/script/e2e_cleanup.sh
  test/script/e2e_kafka.sh
  test/script/event_exporter_inventory.sh
  test/script/event_exporter_kafka.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1118 :bug: Add managedclustermigration example
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/samples/global_hub_v1alpha1_managedclustermigration.yaml
  operator/config/samples/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes

#1114 revert cma when uninstall globalhub
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/controllers/addons/addons_controller.go
  operator/pkg/controllers/addons/addons_controller_test.go
  operator/pkg/controllers/hubofhubs/controller.go
  operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
  operator/pkg/controllers/hubofhubs/prune/prune_reconciler_test.go
  operator/pkg/controllers/hubofhubs/webhook/manifests/addondeploymentconfig.yaml
  operator/pkg/controllers/hubofhubs/webhook/manifests/managedclustersetbinding.yaml
  operator/pkg/controllers/hubofhubs/webhook/manifests/placement.yaml
  test/integration/operator/addons/addons_hosted_test.go
  test/integration/operator/addons/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1110 Have a migration controller to reconcile the managedclustermigation CR
  Makefile
  go.mod
  go.sum
  manager/Containerfile.operator
  manager/Dockerfile
  manager/cmd/manager/main.go
  manager/pkg/config/manager_scheme.go
  manager/pkg/migration/migration_controller.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/hubofhubs/controller.go
  operator/pkg/controllers/hubofhubs/manager/manifests/clusterrole.yaml
  pkg/constants/constants.go
  test/integration/manager/controller/backup_test.go
  test/integration/manager/controller/migration_test.go
  test/integration/manager/controller/suite_test.go
  test/manifest/crd/0000_06_authentication.open-cluster-management.io_managedserviceaccounts.crd.yaml
Labels: lgtm, approved, dco-signoff: yes

#1122 refactor globalhub status
  operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
  operator/api/operator/v1alpha4/zz_generated.deepcopy.go
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/cmd/main.go
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/pkg/config/condition.go
  operator/pkg/config/condition_test.go
  operator/pkg/config/transport_config.go
  operator/pkg/controllers/backup/backup_reconcile.go
  operator/pkg/controllers/hubofhubs/controller.go
  operator/pkg/controllers/hubofhubs/status/status_reconciler.go
  operator/pkg/controllers/hubofhubs/storage/storage_reconciler.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_kafka_controller.go
  operator/pkg/controllers/status/status_reconciler.go
  operator/pkg/controllers/status/status_reconciler_test.go
  test/e2e/backup_test.go
  test/e2e/grafana_test.go
  test/e2e/suite_test.go
  test/integration/operator/agent/suite_test.go
  test/integration/operator/hubofhubs/controller_test.go
  test/integration/utils/testpostgres/testpostgres.go
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1121 :bug: Create inventory always
  operator/pkg/controllers/hubofhubs/storage/manifests.sts/init-configmap.yaml
Labels: lgtm, approved, dco-signoff: yes

#1127 :bug: Owned CRDs should have resources specified
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1111 ✨ support managedcluster migration event.
  agent/cmd/agent/main.go
  agent/pkg/config/scheme.go
  agent/pkg/controllers/crd_controller.go
  agent/pkg/spec/controller/controller.go
  agent/pkg/spec/controller/syncers/dispatcher.go
  agent/pkg/spec/controller/syncers/generic_syncer.go
  agent/pkg/spec/controller/syncers/migration_from_syncer.go
  agent/pkg/spec/controller/syncers/migration_from_syncer_test.go
  agent/pkg/spec/controller/syncers/migration_to_syncer.go
  agent/pkg/spec/controller/syncers/migration_to_syncer_test.go
  manager/cmd/manager/main.go
  manager/pkg/config/manager_config.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/specsyncer/db2transport/syncer/dbsyncer/generic_db_to_transport_syncer.go
  manager/pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_labels_db_to_transport_syncer.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/hubofhubs/controller.go
  operator/pkg/controllers/hubofhubs/manager/manifests/deployment.yaml
  pkg/bundle/event/managedcluster_migration_event.go
  pkg/constants/constants.go
  pkg/transport/producer/generic_producer.go
  pkg/utils/object.go
  test/integration/agent/spec/clusterlabel_syncer_test.go
  test/integration/agent/spec/generic_syncer_test.go
  test/integration/agent/spec/resync_syncer_test.go
  test/integration/agent/spec/suite_test.go
  test/integration/manager/controller/migration_test.go
  test/integration/manager/controller/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1124 fix default ns in hosted mode
  operator/pkg/controllers/addons/addons_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1126 :sparkles: Use inventory api community image
  operator/Makefile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
  operator/pkg/config/multiclusterglobalhub_config.go
Labels: lgtm, approved, dco-signoff: yes

#1128 fix managedcluster watch do not work
  operator/pkg/controllers/crd/crd_controller.go
  test/e2e/cluster_test.go
Labels: lgtm, approved, dco-signoff: yes

#1130 Fix uninstall error
  operator/pkg/config/condition.go
  operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
Labels: lgtm, approved, dco-signoff: yes

#1129 enhance managedcluster migration controller and syncers.
  agent/pkg/spec/controller/controller.go
  agent/pkg/spec/controller/syncers/clusterlabel_syncer.go
  agent/pkg/spec/controller/syncers/dispatcher.go
  agent/pkg/spec/controller/syncers/generic_syncer.go
  agent/pkg/spec/controller/syncers/interface.go
  agent/pkg/spec/controller/syncers/migration_from_syncer.go
  agent/pkg/spec/controller/syncers/migration_from_syncer_test.go
  agent/pkg/spec/controller/syncers/migration_to_syncer.go
  agent/pkg/spec/controller/syncers/migration_to_syncer_test.go
  agent/pkg/spec/controller/syncers/resync_syncer.go
  manager/pkg/migration/migration_controller.go
  pkg/constants/constants.go
  test/integration/manager/controller/migration_test.go
Labels: lgtm, approved, dco-signoff: yes

#1120 :sparkles: Kafka resource reconcile deadlock
  operator/pkg/controllers/hubofhubs/transporter/protocol/byo_transporter.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  operator/pkg/controllers/hubofhubs/transporter/transport_reconciler.go
Labels: lgtm, approved, dco-signoff: yes

#1133 clean up managed clusters after migration is done.
  agent/pkg/spec/controller/syncers/migration_from_syncer.go
  agent/pkg/spec/controller/syncers/migration_from_syncer_test.go
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1136 fix unintall panic
  operator/pkg/controllers/hubofhubs/controller.go
Labels: lgtm, approved, dco-signoff: yes

#1137 :bug: Update kessel to match stolostron/inventory-api
  go.mod
  go.sum
  pkg/transport/inventory/transfer/k8s_cluster.go
Labels: lgtm, approved, dco-signoff: yes

#1138 allow to query migration.from hub in database.
  manager/pkg/migration/migration_controller.go
  test/integration/manager/controller/migration_test.go
  test/integration/manager/controller/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1135 :bug: Add annotations to the managedcluster if the global hub addon is there
  operator/pkg/controllers/crd/crd_controller.go
  operator/pkg/utils/utils.go
  operator/pkg/utils/utils_test.go
  test/e2e/cluster_test.go
Labels: lgtm, approved, dco-signoff: yes

#1141 rove lock in crd controller
  operator/pkg/controllers/crd/crd_controller.go
Labels: dco-signoff: yes

#1134 fix kafka components status
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
  operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter_test.go
  operator/pkg/controllers/status/status_reconciler.go
  operator/pkg/controllers/status/status_reconciler_test.go
  test/e2e/suite_test.go
Labels: dco-signoff: yes

#1145 :seedling: Update Konflux to use release-2.12 branch
  .tekton/multicluster-global-hub-agent-globalhub-1-3-pull-request.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-3-pull-request.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-3-pull-request.yaml
Labels: approved, dco-signoff: yes

#1146 fix annotation did not added
  operator/pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#1148 fix policy number is not right
  agent/pkg/status/controller/generic/generic_event_syncer.go
Labels: lgtm, approved, dco-signoff: yes

#1123 :bug: Increment version in stackrox syncer
  agent/pkg/status/controller/security/stackrox_syncer.go
  test/integration/manager/status/security_alert_counts_handler_test.go
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1139 :sparkles: Add clusterInfo updating/deleting for inventory API
  agent/cmd/agent/main.go
  agent/pkg/controllers/crd_controller.go
  agent/pkg/status/controller/controller.go
  agent/pkg/status/controller/managedclusters/k8s_cluster_test.go
  agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go
  agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer_test.go
  go.mod
  go.sum
  manager/cmd/manager/main.go
  operator/pkg/config/transport_config.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/transport/interface.go
  pkg/transport/inventory/client/client.go
  pkg/transport/inventory/client/client_test.go
  pkg/transport/inventory/transfer/k8s_cluster.go
  pkg/transport/producer/generic_producer.go
  pkg/transport/producer/generic_producer_test.go
  pkg/transport/requester/inventory_client.go
  samples/inventory/requester/global_hub.go
  samples/inventory/requester/main.go
  samples/inventory/requester/managed_hub.go
  test/script/event_exporter_inventory.sh
Labels: lgtm, approved, dco-signoff: yes
