Repository stolostron/multicluster-global-hub, pull requests merged in 2025-04, with the labels that each got.

#1509 Upgrade addon framework to 0.12.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1511 :bug: set importClusterInHosted from mgh annotation
  operator/pkg/controllers/webhook/webhook_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1528 pin 1.2.3 verion
  operator/Makefile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1527 pin 1.4.1 bundle version
  operator/Makefile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1518 fix local agent restart
  operator/pkg/controllers/agent/local_agent_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1517 :sparkles: Refactor generic producer and consumer so that it can be used by migration controller
  Makefile
  agent/cmd/main.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  manager/cmd/main.go
  operator/Makefile
  operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/pkg/config/transport_config.go
  operator/pkg/controllers/transporter/protocol/byo_transporter.go
  operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka-user.yaml
  operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  pkg/transport/assembler_test.go
  pkg/transport/consumer/generic_consumer.go
  pkg/transport/consumer/generic_consumer_test.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/transport/interface.go
  pkg/transport/kafka_config.go
  pkg/transport/producer/generic_producer.go
  pkg/transport/producer/generic_producer_test.go
  pkg/transport/transport_mocks.go
  pkg/transport/type.go
  test/integration/agent/spec/suite_test.go
  test/integration/agent/status/suite_test.go
  test/integration/manager/controller/hub_management_test.go
  test/integration/manager/controller/migration_test.go
  test/integration/manager/controller/suite_test.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/migration/suite_test.go
  test/integration/manager/spec/suite_test.go
  test/integration/manager/status/suite_test.go
  test/integration/operator/controllers/transporter_test.go
  test/manifest/kafka/kafka-cluster/kafka-topics.yaml
  test/script/kessel_e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1532 :bug: Enhance e2e
  agent/pkg/spec/dispatcher.go
  test/e2e/localpolicy_test.go
  test/script/e2e_prow.sh
  test/script/e2e_run.sh
  test/script/e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1533 fix agent log level
  agent/pkg/status/syncers/configmap/config_controller.go
  operator/pkg/controllers/agent/local_agent_controller.go
  operator/pkg/controllers/agent/manifests/configmap.yaml
  operator/pkg/controllers/agent/standalone_agent_controller.go
  operator/pkg/controllers/agent/standalone_agent_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#1494 :sparkles: cleanup the migration resources
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  manager/pkg/controllers/migration_controller.go
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_deploying.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_registering.go
  manager/pkg/status/conflator/conflation_priority.go
  manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
  manager/pkg/status/handlers/handlers.go
  manager/pkg/status/handlers/managedcluster/klusterlet_addon_config_handler.go
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/config/rbac/role.yaml
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/manager/manifests/clusterrole.yaml
  pkg/bundle/migration/managedcluster_migration.go
  pkg/enum/event_type.go
  test/integration/manager/controller/migration_test.go
  test/integration/manager/controller/suite_test.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/status/managedclusetrmigration_handler_test.go
Labels: lgtm, approved, dco-signoff: yes

#1541 Bump to 1.5.0
  operator/Makefile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/metadata/annotations.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1542 Manually upgrade operator subscription, controller runtime, speicedb
  go.mod
  go.sum
Labels: approved, dco-signoff: yes

#1543 fix redundant log in agent
  agent/pkg/status/syncers/events/handlers/local_root_policy_handler.go
  agent/pkg/status/syncers/policies/handlers/status_event_handler.go
Labels: dco-signoff: yes

#1540 disable migration cases in e2e
  test/script/e2e_run_qe.sh
Labels: lgtm, approved, dco-signoff: yes

#1536 :sparkles: Migrate managed clusters
  agent/cmd/main.go
  agent/cmd/main_test.go
  agent/pkg/controllers/init_controller.go
  agent/pkg/spec/spec.go
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  go.mod
  manager/cmd/main.go
  manager/pkg/configs/scheme.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_initializing.go
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/config/rbac/role.yaml
  operator/pkg/controllers/agent/addon/default_agent_controller.go
  operator/pkg/controllers/agent/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/agent/local_agent_controller.go
  operator/pkg/controllers/agent/manifests/clusterrole.yaml
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/manager/manifests/clusterrole.yaml
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter_test.go
  pkg/bundle/migration/managedcluster_migration.go
  pkg/enum/event_type.go
  pkg/transport/config/confluent_config.go
  pkg/utils/utils.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/migration/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1544 :seedling: Rename the condition type and phase
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  go.sum
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_deploying.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_registering.go
  manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/status/managedclusetrmigration_handler_test.go
Labels: lgtm, approved, dco-signoff: yes

#1545 :sparkles: Add cluster validation before starting migration process
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_deploying.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_registering.go
  manager/pkg/migration/migration_validating.go
  test/integration/manager/migration/migration_test.go
Labels: lgtm, approved, dco-signoff: yes

#1547 :seedling: Remove the duplicated kafka message
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_deploying.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_registering.go
  test/integration/manager/migration/migration_test.go
Labels: lgtm, approved, dco-signoff: yes

#1549 :bug: Show the phase status in migration
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
Labels: lgtm, approved, dco-signoff: yes

#1563 :bug: Use transporter to cleanup the kafka resources when disable local agent
  operator/pkg/controllers/agent/local_agent_controller.go
  operator/pkg/controllers/agent/local_agent_controller_test.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
Labels: lgtm, approved, dco-signoff: yes

#1548 :sparkles: Hub validation for migration resource
  manager/pkg/migration/migration_validating.go
  test/integration/manager/migration/migration_test.go
Labels: lgtm, approved, dco-signoff: yes

#1550 :bug: Remove the migration when deleting the global hub cr
  operator/pkg/config/scheme_config.go
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/meta.go
  test/integration/operator/controllers/manager_test.go
Labels: lgtm, approved, dco-signoff: yes

#1567 :bug: Fix integration issue
  operator/pkg/controllers/agent/standalone_agent_controller.go
  test/integration/operator/controllers/agent/standalone_agent/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1564 :seedling: Add registering condition in migration cr
  manager/pkg/migration/migration_registering.go
Labels: lgtm, approved, dco-signoff: yes

#1566 :bug: retry to start producer and consumers
  agent/pkg/spec/syncers/migration_to_syncer.go
  manager/pkg/migration/migration_initializing.go
  operator/pkg/controllers/agent/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
  operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka-user.yaml
  pkg/transport/config/confluent_config.go
Labels: lgtm, approved, dco-signoff: yes

#1565 :bug: Agent addon unkonwn caused by the manifestwork render
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1568 :seedling: Isolate different migration messages in the Kafka topic
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_registering.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  pkg/bundle/migration/managedcluster_migration.go
  samples/kafka/kube_resources/kafka-topic.yaml
  samples/kafka/kube_resources/kafka-user.yaml
  test/integration/manager/migration/migration_test.go
Labels: lgtm, approved, dco-signoff: yes

#1572 :seedling: Use fixed commit sha for kessel
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/manager/manager.yaml
Labels: lgtm, approved, dco-signoff: yes

#1571 :bug: Resend msg
  agent/pkg/spec/dispatcher.go
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  pkg/transport/assembler_test.go
  pkg/transport/consumer/generic_consumer.go
  pkg/transport/controller/controller.go
  pkg/transport/producer/generic_producer.go
  pkg/transport/producer/generic_producer_test.go
  test/integration/agent/spec/suite_test.go
  test/integration/agent/status/suite_test.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/migration/suite_test.go
  test/integration/manager/spec/suite_test.go
  test/integration/manager/status/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1570 :sparkles: Initializing migration
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
  pkg/bundle/migration/managedcluster_migration.go
  samples/cloudevent/confluent-receiver/main.go
  samples/cloudevent/confluent-sender/main.go
  samples/config/confluent_config.go
  samples/kafka/confluent_admin/main.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/status/managedclusetrmigration_handler_test.go
Labels: lgtm, approved, dco-signoff: yes

#1593 :bug: Fix the integration test
  agent/pkg/status/filter/time_filter.go
  agent/pkg/status/filter/time_filter_test.go
  test/integration/agent/status/localpolicy_event_test.go
Labels: lgtm, approved, dco-signoff: yes

#1589 :bug: Fix UT and integration test
  pkg/transport/controller/controller_test.go
  test/integration/agent/status/managedcluster_event_test.go
Labels: lgtm, approved, dco-signoff: yes

#1585 :sparkles: Event status
  manager/pkg/migration/migration_eventstatus.go
  manager/pkg/migration/migration_eventstatus_test.go
  manager/pkg/migration/migration_validating.go
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
Labels: lgtm, approved, dco-signoff: yes

#1535 Move inventory
  agent/pkg/controllers/clusterclaim_version_controller.go
  agent/pkg/controllers/init_controller.go
  agent/pkg/controllers/inventory/inventory.go
  agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller.go
  agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller_test.go
  agent/pkg/controllers/inventory/policy/policy_controller.go
  agent/pkg/controllers/inventory/policy/policy_controller_test.go
  agent/pkg/status/syncers/managedhub/cluster_info_syncer.go
  go.mod
  go.sum
  manager/cmd/main.go
  manager/pkg/configs/config.go
  manager/pkg/status/conflator/conflation_manager.go
  manager/pkg/status/handlers/handlers.go
  manager/pkg/status/handlers/managedcluster/managedcluster_handler.go
  manager/pkg/status/handlers/managedcluster/managedcluster_handler_test.go
  manager/pkg/status/status.go
  operator/pkg/certificates/certificates.go
  operator/pkg/certificates/certificates_test.go
  operator/pkg/config/transport_config.go
  operator/pkg/controllers/agent/addon/addon_agent_manifest_transport.go
  operator/pkg/controllers/agent/addon/addon_manager.go
  operator/pkg/controllers/agent/manifests/clusterrole.yaml
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/manager/manifests/deployment.yaml
  operator/pkg/controllers/manager/manifests/transport-config-secret.yaml
  pkg/bundle/cluster/hub_cluster_info_bundle.go
  pkg/constants/constants.go
  pkg/database/models/common.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/utils/object.go
  samples/inventory/requester/global_hub.go
  samples/inventory/requester/managed_hub.go
  test/e2e/kessel/inventory_test.go
  test/e2e/suite_test.go
  test/integration/agent/status/localpolicy_event_test.go
  test/integration/agent/status/localpolicy_test.go
  test/integration/agent/status/managedcluster_event_test.go
  test/integration/agent/status/suite_test.go
  test/integration/manager/status/managedcluster_event_handler_test.go
  test/integration/manager/status/managedcluster_handler_test.go
  test/integration/manager/status/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1596 :seedling: using the migration status in the initializing stage/phase
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/status/managedclusetrmigration_handler_test.go
Labels: lgtm, approved, dco-signoff: yes

#1598 :sparkles: Wait for managed clusters are available
  agent/pkg/spec/syncers/migration_from_syncer.go
  agent/pkg/spec/syncers/migration_from_syncer_test.go
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_deploying.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_registering.go
  manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  pkg/bundle/migration/managedcluster_migration.go
  test/integration/manager/migration/migration_test.go
Labels: lgtm, approved, dco-signoff: yes

#1602 :seedling: fix the policy event integration test
  test/integration/agent/status/localpolicy_event_test.go
Labels: lgtm, approved, dco-signoff: yes

#1603 :bug: Correct Konflux Configure
  .tekton/multicluster-global-hub-agent-globalhub-1-5-push.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-5-push.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-5-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1600 :seedling: Remove migration db table
  operator/pkg/controllers/storage/database/2.tables.sql
  operator/pkg/controllers/storage/database/4.trigger.sql
  pkg/database/models/status.go
Labels: lgtm, approved, dco-signoff: yes

#1609 :bug: Fix the manager rbac error for the migration deletion
  operator/pkg/controllers/meta.go
Labels: lgtm, approved, dco-signoff: yes

#1506 :sparkles: Extend migration API to support migrating the specified resources
  operator/api/migration/v1alpha1/managedclustermigration_types.go
  operator/api/migration/v1alpha1/zz_generated.deepcopy.go
  operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1610 :bug: Update renovate according the suggestion from konflux experts
  renovate.json
Labels: lgtm, approved, dco-signoff: yes

#1611 :sparkles: Update bundle
  operator/bundle/konflux-patch.sh
Labels: lgtm, approved, dco-signoff: yes

#1613 Wait for 5 seconds to ensure topic is authorized
  agent/pkg/spec/syncers/migration_from_syncer.go
Labels: lgtm, approved, dco-signoff: yes
