Repository stolostron/multicluster-global-hub, pull requests merged in 2025-09, with the labels that each got.

#1923 Remove debug info
  .github/workflows/auto_code_review.yml
Labels: lgtm, approved, dco-signoff: yes

#1915 add migration cluster list to configmap
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_validating.go
  manager/pkg/migration/migration_validating_test.go
Labels: lgtm, approved, dco-signoff: yes

#1925 Cherry-pick PR #1910 changes to release-2.14
  agent/cmd/main.go
  agent/cmd/main_test.go
  manager/cmd/main.go
  operator/pkg/config/transport_config.go
  operator/pkg/controllers/agent/addon/addon_agent_manifest_transport.go
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/transporter/protocol/byo_transporter.go
  operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
  pkg/transport/config/confluent_config.go
  pkg/transport/consumer/generic_consumer.go
  pkg/transport/consumer/generic_consumer_test.go
  pkg/transport/controller/controller.go
  pkg/transport/controller/controller_test.go
  pkg/transport/kafka_config.go
  pkg/transport/type.go
  test/integration/agent/spec/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1931 fix: improve Go function return patterns for better error handling
  agent/pkg/controllers/init_controller.go
  agent/pkg/status/syncers/security/clients/stackrox_client.go
  agent/pkg/status/syncers/security/clients/stackrox_client_test.go
  agent/pkg/status/syncers/security/stackrox_controller.go
  agent/pkg/status/syncers/security/stackrox_syncer.go
  pkg/transport/controller/controller.go
  test/e2e/utils/render_test.go
Labels: lgtm, approved, dco-signoff: yes

#1935 use pipelineRef
  .github/workflows/go.yml
  .tekton/multicluster-global-hub-agent-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-agent-globalhub-1-4-push.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-4-push.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-4-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1940 remove kubectl apply annotation in migrating bundle
  agent/pkg/spec/migration/migration_from_syncer.go
Labels: lgtm, approved, dco-signoff: yes

#1941 :sparkles: Add migration sequence diagram
  ai-doc/migration-sequence-diagram.md
Labels: lgtm, approved, dco-signoff: yes

#1946 refactor: enhance migration error handling and cluster status tracking
  agent/pkg/spec/migration/migration_to_syncer.go
  agent/pkg/spec/migration/migration_to_syncer_test.go
  manager/pkg/migration/migration_eventstatus.go
  manager/pkg/migration/migration_rollbacking.go
  manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
  pkg/bundle/migration/managedcluster_migration.go
Labels: lgtm, approved, dco-signoff: yes

#1949 fix: correct hub name parsing in ResetMigrationStatus for names with dashes
  agent/pkg/spec/migration/migration_from_syncer.go
  agent/pkg/spec/migration/migration_to_syncer.go
  agent/pkg/spec/migration/migration_to_syncer_test.go
  manager/pkg/migration/migration_eventstatus.go
  manager/pkg/migration/migration_eventstatus_test.go
  manager/pkg/migration/migration_registering.go
Labels: lgtm, approved, dco-signoff: yes

#1948 should NOT handle migration which is created in other namespace
  manager/pkg/migration/migration_pending.go
  test/integration/manager/migration/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1862 migration performance test plan
  doc/migration/global_hub_cluster_migration.md
  doc/migration/migration_performance.md
Labels: lgtm, approved, dco-signoff: yes

#1973 fix the integration test
  test/integration/agent/spec/clusterlabel_syncer_test.go
  test/integration/agent/status/application_test.go
  test/integration/agent/status/globalolicy_test.go
  test/integration/agent/status/localpolicy_test.go
  test/integration/agent/status/placement_test.go
  test/integration/agent/status/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1950 move validating logic to agent
  agent/pkg/spec/migration/migration_from_syncer.go
  agent/pkg/spec/migration/migration_from_syncer_test.go
  agent/pkg/spec/migration/migration_to_syncer.go
  agent/pkg/spec/migration/migration_to_syncer_test.go
  agent/pkg/spec/spec.go
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_eventstatus.go
  manager/pkg/migration/migration_registering.go
  manager/pkg/migration/migration_rollbacking.go
  manager/pkg/migration/migration_validating.go
  manager/pkg/migration/migration_validating_test.go
  test/integration/agent/migration/migration_from_syncer_test.go
  test/integration/agent/migration/migration_to_syncer_test.go
  test/integration/agent/migration/suite_test.go
  test/integration/manager/migration/migration_error_scenarios_test.go
  test/integration/manager/migration/migration_phase_test.go
  test/integration/manager/migration/suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#1972 fix the resync is not trigger some time
  agent/pkg/status/emitters/object_emitter.go
  agent/pkg/status/generic/periodic_syncer.go
  agent/pkg/status/syncers/managedcluster/managed_cluster_syncer.go
Labels: lgtm, approved, dco-signoff: yes

#1979 fix: resolve concurrent map read/write panic in configmap package
  agent/pkg/status/syncers/configmap/config_data.go
Labels: lgtm, approved, dco-signoff: yes

#1978 feat: change migration timeout from cumulative to per-stage
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_controller_test.go
  manager/pkg/migration/migration_initializing.go
  manager/pkg/migration/migration_rollbacking.go
  manager/pkg/migration/migration_validating.go
Labels: lgtm, approved, dco-signoff: yes

#1963 add success and failed clusters in configmap
  manager/pkg/migration/migration_cleaning_test.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_controller_test.go
  manager/pkg/migration/migration_deploying_test.go
  manager/pkg/migration/migration_initializing_test.go
  manager/pkg/migration/migration_pending.go
  manager/pkg/migration/migration_registering.go
  manager/pkg/migration/migration_registering_test.go
  manager/pkg/migration/migration_rollbacking_test.go
  manager/pkg/migration/migration_utils.go
  manager/pkg/migration/migration_utils_test.go
  manager/pkg/migration/migration_validating.go
  manager/pkg/migration/migration_validating_test.go
Labels: lgtm, approved, dco-signoff: yes

#1977 doc: add comprehensive resync mechanism analysis
  ai-doc/resync-mechanism.md
Labels: lgtm, approved, dco-signoff: yes

#1980 Remove containerfile and add bare
  rpms.in.yaml
Labels: lgtm, approved, dco-signoff: yes

#1953 chore(KONFLUX-6210): fix and set name and cpe label for multicluster-global-hub-manager-globalhub-1-4
  manager/Containerfile.manager
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test, ok-to-test

#1952 chore(KONFLUX-6210): fix and set name and cpe label for multicluster-global-hub-agent-globalhub-1-4
  agent/Containerfile.agent
Labels: lgtm, dco-signoff: yes, ok-to-test

#2007 add slack notification
  .tekton/multicluster-global-hub-agent-globalhub-1-6-push.yaml
  .tekton/multicluster-global-hub-manager-globalhub-1-6-push.yaml
  .tekton/multicluster-global-hub-operator-globalhub-1-6-push.yaml
Labels: lgtm, approved, dco-signoff: yes
