Repository stolostron/multicluster-global-hub, pull requests merged in 2025-06, with the labels that each got.

#1712 :bug: Don't install the global hub agent in brownfield mode
  agent/pkg/spec/syncers/migration_from_syncer.go
  operator/pkg/controllers/agent/addon/default_agent_controller.go
  test/e2e/local_agent_test.go
  test/integration/operator/controllers/agent/managedclusteraddon_test.go
Labels: lgtm, approved, dco-signoff: yes

#1727 :bug: skip cleanup when the migration is not initialized
  manager/pkg/migration/migration_cleaning.go
Labels: lgtm, approved, dco-signoff: yes

#1730 MigrationStarted should not have timeout
  manager/pkg/migration/migration_initializing.go
Labels: lgtm, approved, dco-signoff: yes

#1729 :bug: cleanup nil panic
  manager/pkg/migration/migration_cleaning.go
Labels: lgtm, approved, dco-signoff: yes

#1726 :seedling: Correct the registering error message
  agent/pkg/spec/syncers/migration_to_syncer.go
  agent/pkg/spec/syncers/migration_to_syncer_test.go
Labels: lgtm, approved, dco-signoff: yes

#1728 fix mgh can not delete in hosted mode
  operator/pkg/controllers/agent/addon/hosted_agent_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1743 :bug: Remove the feature gate - cluster imported hosted
  doc/global_hub_cluster_migration.md
  doc/reserved_names/README.md
  manager/cmd/main.go
  manager/pkg/configs/config.go
  manager/pkg/migration/migration_controller.go
  operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
  operator/api/operator/v1alpha4/zz_generated.deepcopy.go
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/pkg/config/addon_config.go
  operator/pkg/config/multiclusterglobalhub_config.go
  operator/pkg/controllers/agent/addon/addon_agent.go
  operator/pkg/controllers/agent/addon/default_agent_controller.go
  operator/pkg/controllers/agent/addon/default_agent_controller_test.go
  operator/pkg/controllers/agent/addon/hosted_agent_controller.go
  operator/pkg/controllers/agent/addon/hosted_agent_controller_test.go
  operator/pkg/controllers/manager/manager_reconciler.go
  operator/pkg/controllers/manager/manifests/deployment.yaml
  operator/pkg/controllers/webhook/manifests/addondeploymentconfig.yaml
  operator/pkg/controllers/webhook/manifests/managedclustersetbinding.yaml
  operator/pkg/controllers/webhook/manifests/mutatingwebhookconfiguration.yaml
  operator/pkg/controllers/webhook/manifests/placement.yaml
  operator/pkg/controllers/webhook/webhook_controller.go
  operator/pkg/controllers/webhook/webhook_controller_test.go
  operator/pkg/webhook/admission_handler.go
  pkg/constants/constants.go
  test/e2e/suite_test.go
  test/integration/manager/migration/migration_test.go
  test/integration/manager/migration/suite_test.go
  test/integration/operator/controllers/agent/cluster_none_addon_test.go
  test/integration/operator/controllers/agent/clustermanagementaddon_test.go
  test/integration/operator/controllers/agent/hosted_managedhub/mgh_hosted_test.go
  test/integration/operator/controllers/agent/hosted_managedhub/suite_test.go
  test/integration/operator/controllers/agent/managedclusteraddon_test.go
  test/integration/operator/webhook/admission_handler_test.go
  test/integration/operator/webhook/admission_suite_test.go
  test/script/kessel_e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1744 :bug: Need to wait until the cleanup is done
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_controller_test.go
  manager/pkg/migration/migration_eventstatus.go
  test/script/kessel_e2e_setup.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1745 :book: migration doc crrection
  doc/global_hub_cluster_migration.md
Labels: lgtm, approved, dco-signoff: yes

#1754 specify which stage to use
  rpms.in.yaml
Labels: lgtm, approved, dco-signoff: yes

#1750 import managed cluster into global hub
  operator/pkg/webhook/admission_handler.go
Labels: lgtm, approved, dco-signoff: yes

#1758 Revert "do not collect hosted reginal hub info"
  agent/pkg/status/syncers/managedcluster/managed_cluster_syncer.go
Labels: approved, dco-signoff: no

#1749 do not change local-cluster addon ns in hosted mode
  operator/pkg/controllers/agent/addon/hosted_agent_controller.go
Labels: dco-signoff: yes

#1755 [release-2.13] fix e2e error in 2.13
  test/manifest/kafka/kafka-cluster/kafka-cluster.yaml
  test/script/e2e_prow.sh
  test/script/util.sh
Labels: lgtm, approved, dco-signoff: yes

#1760 :bug: trigger cleaning up process if previous stage failed with timeout
  manager/pkg/migration/migration_cleaning.go
  manager/pkg/migration/migration_controller.go
  manager/pkg/migration/migration_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#1761 :bug: Correct configs format
  .github/workflows/auto_code_review.yml
  rpms.in.yaml
Labels: lgtm, approved, dco-signoff: yes

#1768 :bug: Fix RHACS integration issues
  agent/pkg/status/syncers/security/stackrox_syncer.go
  operator/pkg/controllers/agent/local_agent_controller.go
  operator/pkg/controllers/agent/manifests/deployment.yaml
  operator/pkg/controllers/agent/standalone_agent_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1779 :sparkles: Bump to 1.6
  .github/workflows/go.yml
  .tekton/multicluster-global-hub-agent-globalhub-1-6-pull-request.yaml
  .tekton/multicluster-global-hub-agent-globalhub-1-6-push.yaml
  agent/Containerfile.agent
  manager/Containerfile.manager
  operator/Containerfile.operator
  operator/Makefile
  operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  operator/bundle/metadata/annotations.yaml
  operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1786 :bug: Enlarge the message size to 10MB
  agent/pkg/status/status.go
  pkg/constants/constants.go
  pkg/transport/config/confluent_config.go
  pkg/transport/producer/generic_producer.go
Labels: lgtm, approved, dco-signoff: yes

#1787 :bug: Incomplete data in global hub dashboards
  agent/pkg/status/status.go
  pkg/constants/constants.go
  pkg/transport/config/confluent_config.go
  pkg/transport/producer/generic_producer.go
Labels: approved, dco-signoff: yes
